export const userConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'GETALL_REQUEST',
  GETALL_SUCCESS: 'GETALL_SUCCESS',
  GETALL_FAILURE: 'GETALL_FAILURE'
}